### PR TITLE
fix: handle EPIPE for bsdtar

### LINKED ISSUE #2820: unzipStream: missing error handler on bsdtarProcess.stdin causes unhandled EPIPE crash
## Bug Description                                                                                                                                                                         
                                                                         
  When Appium downloads a remote app (via `appium:app` URL), `unzipStream` in `app-utils.js` pipes the HTTP response stream directly into a `bsdtar` child process for extraction. When `bsdtar` exits (even successfully, exit code 0), its stdin pipe closes. If the HTTP download stream still has buffered data in flight at that moment, Node.js attempts to write it to the closed `bsdtarProcess.stdin` socket — resulting in an `EPIPE` error. Because no error listener is attached to `bsdtarProcess.stdin`, Node.js emits it as an unhandled `error` event and **crashes the entire Appium process**.                                 

  ---

  ## Steps to Reproduce                                                                                                                                                                      
   
  1. Configure a session with `appium:app` pointing to a remote ZIP URL (e.g. Google Cloud Storage signed URL)                                                                               
  2. Start Appium and trigger session creation                           
  3. Appium downloads and extracts the app — process crashes immediately after HTTP response headers are logged
                                                                                                                                                                                             
  ---
                                                                                                                                                                                             
  ## Appium Log                                                          

  [BaseDriver] Response status: 200
  [BaseDriver] Etag: "..."
  [BaseDriver] Last-Modified: ...                                                                                                                                                            
  [BaseDriver] Cache-Control: private, max-age=0                                                                                                                                             
                                                                                                                                                                                             
  node:events:497                                                                                                                                                                            
        throw er; // Unhandled 'error' event                             

  Error: write EPIPE
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19)
  Emitted 'error' event on Socket instance at:                                                                                                                                               
      at Socket.onerror (node:internal/streams/readable:1028:14)
      ...                                                                                                                                                                                    
  { errno: -32, code: 'EPIPE', syscall: 'write' }                        
                                                                                                                                                                                             
  ---                                                                    

  ## Root Cause

  In `app-utils.js`, `unzipStream` correctly handles errors on `zipStream` and on `bsdtarProcess` (the ChildProcess), but **not on `bsdtarProcess.stdin`** (the writable Socket):            
   
  ```js                                                                                                                                                                                      
  zipStream.pipe(bsdtarProcess.stdin);                                   
  // ← no error listener on bsdtarProcess.stdin                                                                                                                                              
   
  // ...                                                                                                                                                                                     
  bsdtarProcess.once('error', (e) => { ... }); // handles spawn errors   
  zipStream.once('error', reject);              // handles HTTP stream errors                                                                                                                
  // bsdtarProcess.stdin errors are unhandled ✗                                                                                                                                              
```
  When bsdtar exits while the pipe is still flushing buffered HTTP data, EPIPE fires on bsdtarProcess.stdin with no handler, causing Node.js to throw it as a fatal uncaught exception.      

  ---

##  Proposed Fix                                                           
                                                                                                                                                                                             
 Add an error listener on bsdtarProcess.stdin immediately after the pipe:

```
  zipStream.pipe(bsdtarProcess.stdin);
  bsdtarProcess.stdin.on('error', (e) => {
      if (e.code !== 'EPIPE') {                                                                                                                                                              
          log.warn(`bsdtar stdin error: ${e.message}`);
      }                                                                                                                                                                                      
      // EPIPE is expected when bsdtar exits while the HTTP stream is still flushing.
      // The actual result is already captured via the bsdtarProcess exit/error handlers.                                                                                                    
  });   
```                                                                 
                                                                                                                                                                                             
  ---                                                                    
 ## Environment
             
```  

  ┌────────────────────────┬─────────────────────────────────────────────────────┐
  │ appium-xcuitest-driver │ Confirmed in all versions from 9.9.6 through 11.0.1 │                                                                                                           
  ├────────────────────────┼─────────────────────────────────────────────────────┤
  │ appium                 │ 3.3.1                                               │                                                                                                           
  ├────────────────────────┼─────────────────────────────────────────────────────┤
  │ Node.js                │ Reproduced on both v22.22.2 and v25.8.0             │                                                                                                           
  ├────────────────────────┼─────────────────────────────────────────────────────┤
  │ Platform               │ macOS (Apple Silicon), iOS Simulator                │
  └────────────────────────┴─────────────────────────────────────────────────────┘

```

### PR DESCRIPTION
**Pull request by KazuCocoa**
closes https://github.com/appium/appium-xcuitest-driver/issues/2820

### CODE REVIEW

File: lib/app-utils.ts [hunk 1]
```diff
@@ -277,6 +277,11 @@ export async function unzipStream(zipStream: Readable): Promise<UnzipInfo> {
       log.warn(stderr);
     }
   });
+  bsdtarProcess.stdin.on('error', (e) => {
+    if (!(typeof e === 'object' && e && 'code' in e && e.code === 'EPIPE')) {
```
Comment (mykola-mokhnach) [inline lib/app-utils.ts]: not sure if we need this condition. Can we just log all errors?

Comment (KazuCocoa) [reply lib/app-utils.ts]: No much opinions for that. Simplified

**Review by mykola-mokhnach — APPROVED** [review]
